server:
  port: 8887

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mychatgpt?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ttpfx.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


gpt:
  model:
    key: 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
    url: https://api.openai.com/v1/chat/completions
    name: "gpt-3.5-turbo"
  proxy:
    host: 127.0.0.1
    port: 8887